stages:
  DataGeneration_AddDataH5MD:
    cmd: zntrack run ipsuite.data_loading.add_data_h5md.AddDataH5MD --name DataGeneration_AddDataH5MD
    deps:
    - data/traditional_md.h5
    metrics:
    - nodes/DataGeneration/AddDataH5MD/node-meta.json:
        cache: false
  DataGeneration_AddDataH5MD_1:
    cmd: zntrack run ipsuite.data_loading.add_data_h5md.AddDataH5MD --name DataGeneration_AddDataH5MD_1
    deps:
    - data/enhanced_md.h5
    metrics:
    - nodes/DataGeneration/AddDataH5MD_1/node-meta.json:
        cache: false
  DataGeneration_FixEnergy:
    cmd: zntrack run src.FixEnergy --name DataGeneration_FixEnergy
    deps:
    - nodes/DataGeneration/RandomSelection/node-meta.json
    - nodes/DataGeneration/RandomSelection/selected_ids.json
    - nodes/DataGeneration/RandomSelection/selection.png
    metrics:
    - nodes/DataGeneration/FixEnergy/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/FixEnergy/frames.h5
  DataGeneration_FixEnergy_1:
    cmd: zntrack run src.FixEnergy --name DataGeneration_FixEnergy_1
    deps:
    - nodes/DataGeneration/RandomSelection_1/node-meta.json
    - nodes/DataGeneration/RandomSelection_1/selected_ids.json
    - nodes/DataGeneration/RandomSelection_1/selection.png
    metrics:
    - nodes/DataGeneration/FixEnergy_1/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/FixEnergy_1/frames.h5
  DataGeneration_FixEnergy_2:
    cmd: zntrack run src.FixEnergy --name DataGeneration_FixEnergy_2
    deps:
    - nodes/DataGeneration/RandomSelection_2/node-meta.json
    - nodes/DataGeneration/RandomSelection_2/selected_ids.json
    - nodes/DataGeneration/RandomSelection_2/selection.png
    metrics:
    - nodes/DataGeneration/FixEnergy_2/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/FixEnergy_2/frames.h5
  DataGeneration_OrcaSinglePoint:
    cmd: zntrack run ipsuite.calculators.orca.OrcaSinglePoint --name DataGeneration_OrcaSinglePoint
    deps:
    - nodes/DataGeneration/FixEnergy/frames.h5
    metrics:
    - nodes/DataGeneration/OrcaSinglePoint/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/OrcaSinglePoint/orca
    - nodes/DataGeneration/OrcaSinglePoint/structures.h5
    params:
    - DataGeneration_OrcaSinglePoint
  DataGeneration_OrcaSinglePoint_1:
    cmd: zntrack run ipsuite.calculators.orca.OrcaSinglePoint --name DataGeneration_OrcaSinglePoint_1
    deps:
    - nodes/DataGeneration/FixEnergy_1/frames.h5
    metrics:
    - nodes/DataGeneration/OrcaSinglePoint_1/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/OrcaSinglePoint_1/orca
    - nodes/DataGeneration/OrcaSinglePoint_1/structures.h5
    params:
    - DataGeneration_OrcaSinglePoint_1
  DataGeneration_OrcaSinglePoint_2:
    cmd: zntrack run ipsuite.calculators.orca.OrcaSinglePoint --name DataGeneration_OrcaSinglePoint_2
    deps:
    - nodes/DataGeneration/FixEnergy_2/frames.h5
    metrics:
    - nodes/DataGeneration/OrcaSinglePoint_2/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/OrcaSinglePoint_2/orca
    - nodes/DataGeneration/OrcaSinglePoint_2/structures.h5
    params:
    - DataGeneration_OrcaSinglePoint_2
  DataGeneration_RandomSelection:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      DataGeneration_RandomSelection
    deps:
    - nodes/DataGeneration/AddDataH5MD/node-meta.json
    metrics:
    - nodes/DataGeneration/RandomSelection/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/RandomSelection/selected_ids.json
    - nodes/DataGeneration/RandomSelection/selection.png
    params:
    - DataGeneration_RandomSelection
  DataGeneration_RandomSelection_1:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      DataGeneration_RandomSelection_1
    deps:
    - nodes/DataGeneration/RandomSelection/node-meta.json
    - nodes/DataGeneration/RandomSelection/selected_ids.json
    - nodes/DataGeneration/RandomSelection/selection.png
    metrics:
    - nodes/DataGeneration/RandomSelection_1/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/RandomSelection_1/selected_ids.json
    - nodes/DataGeneration/RandomSelection_1/selection.png
    params:
    - DataGeneration_RandomSelection_1
  DataGeneration_RandomSelection_2:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      DataGeneration_RandomSelection_2
    deps:
    - nodes/DataGeneration/AddDataH5MD_1/node-meta.json
    metrics:
    - nodes/DataGeneration/RandomSelection_2/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/RandomSelection_2/selected_ids.json
    - nodes/DataGeneration/RandomSelection_2/selection.png
    params:
    - DataGeneration_RandomSelection_2
  DataGeneration_ShuffleAndSelect:
    cmd: zntrack run src.ShuffleAndSelect --name DataGeneration_ShuffleAndSelect
    deps:
    - nodes/DataGeneration/OrcaSinglePoint/orca
    - nodes/DataGeneration/OrcaSinglePoint/structures.h5
    metrics:
    - nodes/DataGeneration/ShuffleAndSelect/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/ShuffleAndSelect/frames.h5
    params:
    - DataGeneration_ShuffleAndSelect
  DataGeneration_ShuffleAndSelect_1:
    cmd: zntrack run src.ShuffleAndSelect --name DataGeneration_ShuffleAndSelect_1
    deps:
    - nodes/DataGeneration/OrcaSinglePoint_1/orca
    - nodes/DataGeneration/OrcaSinglePoint_1/structures.h5
    metrics:
    - nodes/DataGeneration/ShuffleAndSelect_1/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/ShuffleAndSelect_1/frames.h5
    params:
    - DataGeneration_ShuffleAndSelect_1
  DataGeneration_ShuffleAndSelect_2:
    cmd: zntrack run src.ShuffleAndSelect --name DataGeneration_ShuffleAndSelect_2
    deps:
    - nodes/DataGeneration/OrcaSinglePoint_2/orca
    - nodes/DataGeneration/OrcaSinglePoint_2/structures.h5
    metrics:
    - nodes/DataGeneration/ShuffleAndSelect_2/node-meta.json:
        cache: false
    outs:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    params:
    - DataGeneration_ShuffleAndSelect_2
  ModelMetrics_ApaxBatchPrediction:
    cmd: zntrack run apax.nodes.analysis.ApaxBatchPrediction --name ModelMetrics_ApaxBatchPrediction
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelTraining/Apax/apax_model
    - nodes/ModelTraining/Apax/metrics.json
    - nodes/ModelTraining/Apax/train_atoms.extxyz
    - nodes/ModelTraining/Apax/val_atoms.extxyz
    metrics:
    - nodes/ModelMetrics/ApaxBatchPrediction/node-meta.json:
        cache: false
    outs:
    - nodes/ModelMetrics/ApaxBatchPrediction/frames.h5
    params:
    - ModelMetrics_ApaxBatchPrediction
  ModelMetrics_ApaxBatchPrediction_1:
    cmd: zntrack run apax.nodes.analysis.ApaxBatchPrediction --name ModelMetrics_ApaxBatchPrediction_1
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelTraining/Apax_1/apax_model
    - nodes/ModelTraining/Apax_1/metrics.json
    - nodes/ModelTraining/Apax_1/train_atoms.extxyz
    - nodes/ModelTraining/Apax_1/val_atoms.extxyz
    metrics:
    - nodes/ModelMetrics/ApaxBatchPrediction_1/node-meta.json:
        cache: false
    outs:
    - nodes/ModelMetrics/ApaxBatchPrediction_1/frames.h5
    params:
    - ModelMetrics_ApaxBatchPrediction_1
  ModelMetrics_ApaxBatchPrediction_2:
    cmd: zntrack run apax.nodes.analysis.ApaxBatchPrediction --name ModelMetrics_ApaxBatchPrediction_2
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelTraining/Apax_2/apax_model
    - nodes/ModelTraining/Apax_2/metrics.json
    - nodes/ModelTraining/Apax_2/train_atoms.extxyz
    - nodes/ModelTraining/Apax_2/val_atoms.extxyz
    metrics:
    - nodes/ModelMetrics/ApaxBatchPrediction_2/node-meta.json:
        cache: false
    outs:
    - nodes/ModelMetrics/ApaxBatchPrediction_2/frames.h5
    params:
    - ModelMetrics_ApaxBatchPrediction_2
  ModelMetrics_PredictionMetrics:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name ModelMetrics_PredictionMetrics
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelMetrics/ApaxBatchPrediction/frames.h5
    metrics:
    - nodes/ModelMetrics/PredictionMetrics/energy.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics/forces.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics/node-meta.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics/stress.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics/stress_deviat.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics/stress_hydro.json:
        cache: false
    outs:
    - nodes/ModelMetrics/PredictionMetrics/data.npz
    - nodes/ModelMetrics/PredictionMetrics/plots
    params:
    - ModelMetrics_PredictionMetrics
  ModelMetrics_PredictionMetrics_1:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name ModelMetrics_PredictionMetrics_1
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelMetrics/ApaxBatchPrediction_1/frames.h5
    metrics:
    - nodes/ModelMetrics/PredictionMetrics_1/energy.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_1/forces.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_1/node-meta.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_1/stress.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_1/stress_deviat.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_1/stress_hydro.json:
        cache: false
    outs:
    - nodes/ModelMetrics/PredictionMetrics_1/data.npz
    - nodes/ModelMetrics/PredictionMetrics_1/plots
    params:
    - ModelMetrics_PredictionMetrics_1
  ModelMetrics_PredictionMetrics_2:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name ModelMetrics_PredictionMetrics_2
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelMetrics/ApaxBatchPrediction_2/frames.h5
    metrics:
    - nodes/ModelMetrics/PredictionMetrics_2/energy.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_2/forces.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_2/node-meta.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_2/stress.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_2/stress_deviat.json:
        cache: false
    - nodes/ModelMetrics/PredictionMetrics_2/stress_hydro.json:
        cache: false
    outs:
    - nodes/ModelMetrics/PredictionMetrics_2/data.npz
    - nodes/ModelMetrics/PredictionMetrics_2/plots
    params:
    - ModelMetrics_PredictionMetrics_2
  ModelTraining_Apax:
    cmd: zntrack run apax.nodes.model.Apax --name ModelTraining_Apax
    deps:
    - nodes/DataGeneration/ShuffleAndSelect/frames.h5
    metrics:
    - nodes/ModelTraining/Apax/metrics.json:
        cache: false
    - nodes/ModelTraining/Apax/node-meta.json:
        cache: false
    outs:
    - nodes/ModelTraining/Apax/apax_model
    - nodes/ModelTraining/Apax/train_atoms.extxyz
    - nodes/ModelTraining/Apax/val_atoms.extxyz
    params:
    - ModelTraining_Apax
    - configs/base_train.yaml: null
  ModelTraining_Apax_1:
    cmd: zntrack run apax.nodes.model.Apax --name ModelTraining_Apax_1
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_1/frames.h5
    - nodes/ModelTraining/Apax/apax_model
    - nodes/ModelTraining/Apax/metrics.json
    - nodes/ModelTraining/Apax/train_atoms.extxyz
    - nodes/ModelTraining/Apax/val_atoms.extxyz
    metrics:
    - nodes/ModelTraining/Apax_1/metrics.json:
        cache: false
    - nodes/ModelTraining/Apax_1/node-meta.json:
        cache: false
    outs:
    - nodes/ModelTraining/Apax_1/apax_model
    - nodes/ModelTraining/Apax_1/train_atoms.extxyz
    - nodes/ModelTraining/Apax_1/val_atoms.extxyz
    params:
    - ModelTraining_Apax_1
    - configs/random_transfer.yaml: null
  ModelTraining_Apax_2:
    cmd: zntrack run apax.nodes.model.Apax --name ModelTraining_Apax_2
    deps:
    - nodes/DataGeneration/ShuffleAndSelect_2/frames.h5
    - nodes/ModelTraining/Apax/apax_model
    - nodes/ModelTraining/Apax/metrics.json
    - nodes/ModelTraining/Apax/train_atoms.extxyz
    - nodes/ModelTraining/Apax/val_atoms.extxyz
    metrics:
    - nodes/ModelTraining/Apax_2/metrics.json:
        cache: false
    - nodes/ModelTraining/Apax_2/node-meta.json:
        cache: false
    outs:
    - nodes/ModelTraining/Apax_2/apax_model
    - nodes/ModelTraining/Apax_2/train_atoms.extxyz
    - nodes/ModelTraining/Apax_2/val_atoms.extxyz
    params:
    - ModelTraining_Apax_2
    - configs/es_transfer.yaml: null
