DataGeneration_OrcaSinglePoint:
  orca_shell: /data/fzills/tools/orca_5_0_4/orca
  orcablocks: '%pal nprocs 8 end'
  orcasimpleinput: PBE def2-TZVP TightSCF EnGrad
DataGeneration_OrcaSinglePoint_1:
  orca_shell: /data/fzills/tools/orca_5_0_4/orca
  orcablocks: '%pal nprocs 8 end'
  orcasimpleinput: PBE def2-TZVP TightSCF EnGrad
DataGeneration_OrcaSinglePoint_2:
  orca_shell: /data/fzills/tools/orca_5_0_4/orca
  orcablocks: '%pal nprocs 8 end'
  orcasimpleinput: PBE def2-TZVP TightSCF EnGrad
DataGeneration_RandomSelection:
  n_configurations: 500
  seed: 1234
DataGeneration_RandomSelection_1:
  n_configurations: 500
  seed: 1234
DataGeneration_RandomSelection_2:
  n_configurations: 500
  seed: 1234
DataGeneration_ShuffleAndSelect:
  n_test: 400
  n_train: 20
  n_validate: 20
  seed: 1234
DataGeneration_ShuffleAndSelect_1:
  n_test: 400
  n_train: 20
  n_validate: 20
  seed: 1234
DataGeneration_ShuffleAndSelect_2:
  n_test: 400
  n_train: 20
  n_validate: 20
  seed: 1234
ModelMetrics_ApaxBatchPrediction:
  batch_size: 10
ModelMetrics_ApaxBatchPrediction_1:
  batch_size: 10
ModelMetrics_ApaxBatchPrediction_2:
  batch_size: 10
ModelMetrics_PredictionMetrics:
  figure_ymax: {}
ModelMetrics_PredictionMetrics_1:
  figure_ymax: {}
ModelMetrics_PredictionMetrics_2:
  figure_ymax: {}
ModelTraining_Apax:
  log_level: info
  nl_skin: 0.5
  transformations: null
ModelTraining_Apax_1:
  log_level: info
  nl_skin: 0.5
  transformations: null
ModelTraining_Apax_2:
  log_level: info
  nl_skin: 0.5
  transformations: null
