n_epochs: 2048
seed: 1

data:
  batch_size: 6
  scale_method: per_element_force_rms_scale
  shift_method: per_element_regression_shift
  shift_options:
    energy_regularisation: 1.0
  valid_batch_size: 128

loss:
- name: energy
  loss_type: crps
- name: forces
  loss_type: crps
  weight: 2.0

metrics:
- name: energy
  reductions:
  - mae
- name: forces
  reductions:
  - mae

model:
  ensemble:
    kind: shallow
    n_members: 8
  name: gmnn
  basis:
    name: bessel
    n_basis: 7
    r_max: 5.5

  n_radial: 5
  nn:
  - 64
  - 64

  w_init: lecun
  b_init: zeros
  use_ntk: false
  emb_init: uniform
  
  calc_stress: false

  descriptor_dtype: fp32
  readout_dtype: fp32
  scale_shift_dtype: fp32

optimizer:
  name: adam
  schedule:
    name: cyclic_cosine
    period: 128
    decay_factor: 0.85
  emb_lr: 0.001
  nn_lr: 0.005
  scale_lr: 0.001
  shift_lr: 0.05